---
version: '3.6'

# To use traefik.io as reverse proxy uncomment this to connect to traefik:
#networks:
#  net-proxy:
#    external: true
#    name: net-proxy   

services:
  odata:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: ${CI_REGISTRY_IMAGE:-docker-registry.rz.uni-bamberg.de/itfl-service/hydra/odata:latest}
    environment:
      CATALINA_OPTS: "-Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true -Xmx2048m -Xms2048m -XX:MaxPermSize=512m"
	  SOLR_URL: "http://localhost:8080/solr/search"
    ports:
      - "8080:8080"

# To use traefik.io as reverse proxy uncomment this and set IMAGE NAME and URL as env vars:
#    networks:
#      net-proxy:
#    labels:
#      traefik.enable: "true"
#      traefik.docker.network: "net-proxy"
#      traefik.backend: "$NAME"
#      traefik.port: "8080"
#      traefik.frontend.rule: "Host:$URL"
#      traefik.frontend.entryPoints: "http"
#      traefik.frontend.passHostHeader: "true"
#      traefik.backend.loadbalancer.stickiness: "true"
